name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the fruitscan-web Docker image
run: |
       docker tag fruitscan-web:latest ghcr.io/mezyn/fruitscan-web:latest
       docker push ghcr.io/mezyn/fruitscan-web:latest