apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ghcr.io/harring/fruitscan:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: sqlite:///app/db.sqlite3
      volumes:
        - name: static-storage
          emptyDir: {}
        - name: media-storage
          emptyDir: {}
        - name: db-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
